### ISSUE TITLE
Invalid dependency when installing through OpenUPM

### ISSUE THREAD

**Issue by MileyHollenberg** [Artees/Unity-Package-Manifest-Generator#1]
Hi, I'm currently trying to install this package through OpenUPM in a Unity 2019.3.14f1 project but I keep getting the following error

```
[WARN] package games.artees.litjson@0.13.2 is not a valid choice of 0.13.1
[WARN] fall back to games.artees.litjson@0.13.1
 added: games.artees.package-manifest-generator@1.0.2
 manifest updated, please open unity project to apply changes
```

It seems like litjson 0.13.2 doesn't yet exist on OpenUPM which is causing the issue, please fix this so I can use your package to create some of my own :)

**Comment by Artees** [comment]
fixed

**Comment by MileyHollenberg** [comment]
Thanks, I can see this issue is indeed fixed but a new one (possibly related to this) rose up saying that there is an infinite loop in the asset

```
An infinite import loop has been detected. The following Assets were imported multiple times, but no changes to them have been detected. Please check if any custom code is trying to import them:
Packages/games.artees.package-manifest-generator/package.jsonpackage
```

I got this right after importing the package and when I restarted Unity I got this error 3 times. It also comes up when I create a Package config and the inspector for it is completely empty

**Comment by Artees** [comment]
I can't reproduce it. Do you see the same error when you import the package into a new project?

**Comment by MileyHollenberg** [comment]
Just created a new project to try this out and I'm getting similar results

Directly after importing I got this error

```
An infinite import loop has been detected. The following Assets were imported multiple times, but no changes to them have been detected. Please check if any custom code is trying to import them:
Packages/games.artees.litjson/doc/out/quickstart.html
Packages/games.artees.package-manifest-generator/package.jsonpackage
```

And when creating a package config (which still didn't show in the inspector) I got these errors

```
An infinite import loop has been detected. The following Assets were imported multiple times, but no changes to them have been detected. Please check if any custom code is trying to import them:
Packages/games.artees.litjson/doc/out/quickstart.html
Assets/package.jsonpackage
Packages/games.artees.package-manifest-generator/package.jsonpackage

UnityEditor.AssetDatabase:CreateAsset(Object, String)
Artees.UnityPackageManifestGenerator.Editor.PackageManifestMenu:Create(MenuCommand) (at Library/PackageCache/games.artees.package-manifest-generator@1.0.2/Editor/PackageManifestMenu.cs:21)
```

I'm trying this on Windows 10 though I doubt this could be platform specific

**Comment by Artees** [comment]
Oh, I can reproduce this on Windows actually. I'll look into it today.

**Comment by Artees** [comment]
The package is updated.
