### ISSUE TITLE
Major lag everytime a new character is added to a field

### ISSUE THREAD

**Issue by MileyHollenberg** [Artees/Unity-Package-Manifest-Generator#2]
I'm trying to start a new package but whenever I try to type the name or description it takes roughly 1 second per character to appear. Is it maybe serializing something on every entry? This doesn't feel right at least. I'm using it on 2019.4 though I had the same issue on 2019.3 as well on Windows 10.

It's not exclusive to those fields, it's happening on all of them. FYI this is the third package in my project that uses this system

**Comment by Artees** [comment]
Fixed. Thanks for testing!
