### ISSUE TITLE
clashing assembly file with other package

### ISSUE THREAD

**Issue by hannesdelbeke** [Artees/Unity-Package-Manifest-Generator#4]
i get a clash with a package from unity (ML-Agents)
![image](https://user-images.githubusercontent.com/3758308/105840810-83d97b00-5fcb-11eb-9cee-77ec12314dab.png)

the assembly should have a unique name in it's settings
unity recommends 
`The name for the assembly (without a file extension). Assembly names must be unique across the Project. Consider using a reverse-DNS naming style to reduce the chance of name conflicts, especially if you want to use the assembly in more than one Project.`

**Comment by hannesdelbeke** [comment]
note this issue is not directly in this repo/ package but in your dependency package

![image](https://user-images.githubusercontent.com/3758308/105841288-46292200-5fcc-11eb-9adf-b9272ba9bdd6.png)

**Comment by hannesdelbeke** [comment]
changed name locally from Tests to Tests2 to avoid clashing 
![image](https://user-images.githubusercontent.com/3758308/105841378-6658e100-5fcc-11eb-99ed-252c212abaa9.png)

**Comment by hannesdelbeke** [comment]
the editor assembly file in that package has a unique name
so the fix would be to do the same for the test assembly
![image](https://user-images.githubusercontent.com/3758308/105841444-8092bf00-5fcc-11eb-9652-07418098398f.png)

**Comment by Artees** [comment]
Have you updated the package to the latest version (1.0.6)?

**Comment by hannesdelbeke** [comment]
i believe i was on 1.0.5
likely since unity version was bumped in 1.0.6 from 2019.3 to 2019.4
and i am on unity 2019.3

i installed it through open upm if i remember correctly

If the tests assembly has been fixed in 1.0.6 this ticket can be closed

**Comment by Artees** [comment]
You should be able to install it on 2019.3 BTW. 2019.4 is the version I tested it with.
