### ISSUE TITLE
when leaving display name blank it auto fills the name with the first name of the package in your project

### ISSUE THREAD

**Issue by hannesdelbeke** [Artees/Unity-Package-Manifest-Generator#5]
**problem**
when leaving display name blank it auto fills the name with the first name of the package in your project

![image](https://user-images.githubusercontent.com/3758308/105842031-85a43e00-5fcd-11eb-9ddf-130a536be2e7.png)

**expected behaviour**
- either do not allow user to press apply if displayname is missing
- or auto fill display name based on name of the toolname field, 
- or autofill a default toolname

**priority**
very low
expected behaviour is that users always will fill in the displayname

**Comment by hannesdelbeke** [comment]
note ML Agent is at the top of the list
![image](https://user-images.githubusercontent.com/3758308/105842330-e6337b00-5fcd-11eb-8dc0-423219d37d66.png)

**Comment by Artees** [comment]
The display name is now autofilled based on the package name: 4407db1f6f19aac342f10a677772f160309cea3f
